import {journalPages} from './journal.mjs';
import {readFile,mkdir,writeFile,readdir,rm} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=dirname(fileURLToPath(import.meta.url));
export const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeLink=x=>typeof x==='string'&&/^https:\/\//.test(x)&&new URL(x).protocol==='https:';
const asset=x=>typeof x==='string'&&/^assets\/[a-zA-Z0-9_/-]+\.(png|jpe?g|webp|avif|pdf)$/.test(x)&&!x.includes('..');
export async function buildAcademic({profile:p,site,out}){
  if(!safeLink(site.url)||!site.url.endsWith('/'))throw Error('Invalid site URL');
  for(const list of ['education','experience','teaching','awards','publications','presentations','news'])for(const entry of p[list]||[])if(entry.verified!==true||['source','url','project','code','preprint'].some(k=>entry[k]&&!safeLink(entry[k])))throw Error('Only verified public records and HTTPS links can be published');
  if(!safeLink(p.labUrl)||!safeLink(p.github)||p.linkedin&&!safeLink(p.linkedin)||p.portrait&&!asset(p.portrait)||p.cvPdf&&!asset(p.cvPdf))throw Error('Invalid public link or asset');
  for(const email of [p.personalEmail,p.academicEmail])if(!/^[A-Za-z0-9._+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(email))throw Error('Invalid contact email');
  if(resolve(out)===join(root,'dist'))await rm(out,{recursive:true,force:true});
  await mkdir(out,{recursive:true});
  const emit=async(path,text)=>{await mkdir(dirname(join(out,path)),{recursive:true});await writeFile(join(out,path),text);};
  const base=new URL(site.url).pathname,href=path=>base+path;
  const external=(url,label,cls='')=>`<a class="${cls}" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)} <span aria-hidden="true">↗</span></a>`;
  const nav=`<a href="${href('')}#about">About</a><a href="${href('')}#work">Work</a><a href="${href('journal/')}">Journal</a><a href="${href('cv/')}">CV</a><a href="${href('')}#contact">Contact</a>`;
  const page=(title,path,body,noindex=false)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c0f10"><title>${escape(title)}</title><meta name="description" content="${escape(site.description)}">${noindex?'<meta name="robots" content="noindex">':''}<link rel="alternate" type="application/rss+xml" title="D-Bae Journal" href="${href('journal/feed.xml')}"><link rel="canonical" href="${escape(new URL(path,site.url))}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(site.description)}">${p.portrait?`<meta property="og:image" content="${escape(new URL(p.portrait,site.url))}"><meta property="og:image:alt" content="${escape(p.name)}">`:''}<meta property="og:type" content="website"><meta property="og:url" content="${escape(new URL(path,site.url))}"><link rel="icon" href="${href('favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${href('style.css')}"><script src="${href('app.js')}" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="${href('')}">D-Bae<span> / ${escape(p.name.toUpperCase())}</span></a><nav aria-label="Main navigation">${nav}</nav></header><main id="main" tabindex="-1">${body}</main><footer><a class="footer-brand" href="${href('')}">D-Bae</a><span>${escape(p.name)} · ${escape(p.institution)}</span><a href="#main">Back to top ↑</a></footer></body></html>`;
  const section=(id,index,label,content)=>`<section class="academic-section" id="${id}"><div class="section-label"><span>${index}</span><h2>${label}</h2></div><div class="section-content">${content}</div></section>`;
  const hero=`<section class="intro academic-hero" aria-labelledby="hero-title"><div class="hero-topline"><p class="eyebrow">${escape(p.institution.toUpperCase())}</p><span class="hero-dot" aria-hidden="true"></span></div><div class="hero-type"><h1 id="hero-title">Donggeon<br><span>Bae.</span></h1></div><div class="hero-bottomline"><div><p class="hero-role">${escape(p.role)}</p><p class="hero-lab">${escape(p.laboratory)}</p></div><a class="scroll-cue" href="#about">Explore <span aria-hidden="true">↓</span></a></div><div class="hero-rule" aria-hidden="true"></div></section>`;
  const about=section('about','01','About',`<div class="about-grid"><div><p class="about-copy reveal">${escape(p.aboutLead)}</p><p class="about-detail">${escape(p.about)}</p><div class="interests">${p.interests.map(x=>`<span>${escape(x)}</span>`).join('')}</div><div class="inline-links">${external(p.labUrl,'Research group')}${p.linkedin?external(p.linkedin,'LinkedIn'):''}<a href="${href('cv/')}">Curriculum vitae ↗</a></div></div>${p.portrait?`<figure class="portrait"><img src="${href(p.portrait)}" alt="Portrait of ${escape(p.name)}" width="200" height="200" loading="lazy" decoding="async"></figure>`:''}</div>`);
  const rows=(items,kind)=>items.length?`<ol class="academic-records">${items.map((r,i)=>`<li class="reveal"><div class="record-meta"><span>${escape(r.date||r.year||'')}</span><span>${escape(r.status||kind)}</span></div><div class="record-content"><h3>${r.url?external(r.url,r.title):escape(r.title)}</h3>${r.authors?`<p class="record-authors">${escape(r.authors).replaceAll('Donggeon Bae','<strong class="own-author">Donggeon Bae</strong>')}</p>`:''}${r.venue?`<p>${escape(r.venue)}</p>`:''}${r.detail?`<p>${escape(r.detail)}</p>`:''}<div class="record-links">${r.preprint?external(r.preprint,'Preprint'):''}${r.project?external(r.project,'Project'):''}${r.code?external(r.code,'Code'):''}${safeLink(r.source)&&r.source!==r.url?`<a class="source-link" href="${escape(r.source)}">Source ↗</a>`:''}</div></div></li>`).join('')}</ol>`:`<p class="record-empty">${kind==='Publication'?'Publication records':kind==='Presentation'?'Conference presentations':'Updates'} will be listed here.</p>`;
  const work=section('work','02','Research',`<div class="subsection-heading"><h3>Publications</h3><span>${String(p.publications.length).padStart(2,'0')}</span></div>${rows(p.publications,'Publication')}<div class="subsection-heading"><h3>Presentations</h3><span>${String(p.presentations.length).padStart(2,'0')}</span></div>${rows(p.presentations,'Presentation')}`);
  const news=section('news','03','News',rows(p.news,'News'));
  const cv=section('cv','04','Curriculum vitae',`<p class="cv-caption">${escape(p.role)}<br>${escape(p.institution)}</p><div class="education-list">${p.education.map(e=>`<div><span>${escape(e.date)}</span><p>${escape(e.degree)}<br><strong>${escape(e.institution)}</strong></p></div>`).join('')}</div><h3 class="cv-teaching-heading">Teaching</h3><div class="education-list teaching-list">${(p.teaching||[]).map(t=>`<div><span>${escape(t.date)}</span><p>${escape(t.title)}<br><strong>${escape(t.institution)}</strong></p></div>`).join('')}</div><div class="inline-links"><a href="${href('cv/')}">View CV <span aria-hidden="true">↗</span></a>${p.cvPdf?`<a href="${href(p.cvPdf)}" download>Download PDF <span aria-hidden="true">↓</span></a>`:''}</div>`);
  const contact=section('contact','05','Contact',`<p class="contact-intro">Get in touch.</p><div class="contact-list"><a href="mailto:${escape(p.personalEmail)}"><span>Personal</span><strong>${escape(p.personalEmail)}</strong><span aria-hidden="true">↗</span></a><a href="mailto:${escape(p.academicEmail)}"><span>Academic</span><strong>${escape(p.academicEmail)}</strong><span aria-hidden="true">↗</span></a><a href="${escape(p.github)}"><span>GitHub</span><strong>donggeonbae</strong><span aria-hidden="true">↗</span></a>${p.linkedin?`<a href="${escape(p.linkedin)}"><span>LinkedIn</span><strong>${escape(p.name)}</strong><span aria-hidden="true">↗</span></a>`:''}</div>`);
  const journal=await journalPages(root,href,escape);
  for(const entry of journal)await emit(entry.path+'index.html',page(entry.title,entry.path,entry.body));
  await emit('index.html',page(p.name,'',hero+about+work+news+cv+contact));
  const cvBody=`<article class="cv-page"><div class="article-heading"><p class="eyebrow">CURRICULUM VITAE · ${escape(p.updated)}</p><h1>${escape(p.name)}</h1><p class="article-deck">${escape(p.role)} · Mechanical Engineering<br>${escape(p.institution)} · ${escape(p.laboratory)}</p><p class="cv-contact">${escape(p.personalEmail)} · ${escape(p.academicEmail)}<br>${external(p.github,'GitHub')} · ${external(p.linkedin,'LinkedIn')}</p>${p.cvPdf?`<a class="cv-download" href="${href(p.cvPdf)}" download>Download PDF ↓</a>`:''}</div><div class="cv-body"><h2>Research interests</h2><p>${p.interests.map(escape).join(' · ')}</p><h2>Education</h2>${p.education.map(e=>`<p><strong>${escape(e.institution)}</strong> · ${escape(e.date)}<br>${escape(e.degree)}${e.detail?`<br>${escape(e.detail)}`:''}</p>`).join('')}<h2>Research experience</h2>${(p.experience||[]).map(e=>`<p><strong>${escape(e.title)}</strong> · ${escape(e.date)}<br>${escape(e.institution)}<br>${escape(e.detail)}</p>`).join('')}<h2>Publications</h2>${rows(p.publications,'Publication')}<section class="cv-second"><h2>Teaching &amp; service</h2>${(p.teaching||[]).map(t=>`<p><strong>${escape(t.title)}</strong> · ${escape(t.date)}<br>${escape(t.institution)}${t.detail?`<br>${escape(t.detail)}`:''}</p>`).join('')}<h2>Conference presentations</h2>${rows(p.presentations,'Presentation')}<h2>Awards</h2>${rows(p.awards||[],'Award')}<p class="cv-source">Updated ${escape(p.updated)}. Accepted and published works are labeled separately. Public profile: <a href="${escape(p.labUrl)}">imaging.snu.ac.kr/team</a>.</p></section></div></article>`;
  await emit('cv/index.html',page(`${p.name} · CV`,'cv/',cvBody).replace('</header>','</header><div class="reading-track" aria-hidden="true"><span></span></div>'));
  const cvMarkdown=`# ${p.name}\n\n${p.role}, Mechanical Engineering\n${p.institution} | ${p.laboratory}\n\n${p.personalEmail} | ${p.academicEmail}\n${p.github}\n${p.linkedin}\n\n## Research interests\n\n${p.interests.join('; ')}\n\n## Education\n\n${p.education.map(e=>`- ${e.institution}, ${e.degree}, ${e.date}${e.detail?'. '+e.detail:''}`).join('\n')}\n\n## Research experience\n\n${(p.experience||[]).map(e=>`- ${e.title}, ${e.institution}, ${e.date}. ${e.detail}`).join('\n')}\n\n## Teaching & service\n\n${(p.teaching||[]).map(t=>`- ${t.title}, ${t.institution}, ${t.date}${t.detail?'. '+t.detail:''}`).join('\n')}\n\n## Publications\n\n${p.publications.map((r,i)=>`${i+1}. ${r.authors}. **${r.title}.** ${r.venue}, ${r.date} (${r.status}). ${r.url}`).join('\n\n')}\n\n## Conference presentations\n\n${p.presentations.map(r=>`- ${r.date} — ${r.title}. ${r.venue} (${r.status}).`).join('\n')}\n\n## Awards\n\n${(p.awards||[]).map(r=>`- ${r.title}, ${r.venue}, ${r.date}.`).join('\n')}\n\nUpdated ${p.updated}.\n`;
  await emit('cv/Donggeon_Bae_CV.md',cvMarkdown);
  await emit('404.html',page('Page not found','404.html','<section class="not-found"><p class="eyebrow">PAGE NOT FOUND</p><h1>404.</h1><p>The page you are looking for could not be found.</p><a href="'+href('')+'">Back to home ↗</a></section>',true));
  await emit('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${escape(site.url)}</loc></url><url><loc>${escape(new URL('cv/',site.url))}</loc></url>${journal.map(e=>`<url><loc>${escape(new URL(e.path,site.url))}</loc></url>`).join('')}</urlset>`);
  await emit('journal/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>D-Bae Journal</title><link>${escape(new URL('journal/',site.url))}</link><description>Photographs, everyday moments, and notes.</description>${journal.slice(1).map(e=>`<item><title>${escape(e.title)}</title><link>${escape(new URL(e.path,site.url))}</link><guid>${escape(new URL(e.path,site.url))}</guid></item>`).join('')}</channel></rss>`);
  await emit('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${new URL('sitemap.xml',site.url)}\n`);await emit('.nojekyll','');
  async function copy(dir,prefix=''){for(const e of await readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink())throw Error('Asset symlinks are not allowed');if(e.isDirectory())await copy(join(dir,e.name),prefix+e.name+'/');else await emit(prefix+e.name,await readFile(join(dir,e.name)));}}
  await copy(join(root,'public'));
  if(p.cvPdf)await emit('CV_BDG.pdf',await readFile(join(root,'public',p.cvPdf)));
  return {pages:3+journal.length,publications:p.publications.length,presentations:p.presentations.length,news:p.news.length,base};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){console.log(await buildAcademic({profile:JSON.parse(await readFile(join(root,'profile.json'),'utf8')),site:JSON.parse(await readFile(join(root,'site.json'),'utf8')),out:join(root,'dist')}));}
