import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
export async function journalPages(root,href,escape){
const posts=JSON.parse(await readFile(join(root,'journal/posts.json'),'utf8'));if(!Array.isArray(posts))throw Error('Journal must be an array');const slugs=new Set();
const publicPosts=posts.filter(p=>p.status==='published');for(const p of publicPosts){if(p.publicApproved!==true||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||isNaN(Date.parse(p.date))||!/^\d{4}-\d{2}-\d{2}$/.test(new Date(p.date).toISOString().slice(0,10))||new Date(p.date).toISOString().slice(0,10)!==p.date||! /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug)||slugs.has(p.slug))throw Error('Invalid or unapproved public Journal entry');slugs.add(p.slug);for(const image of p.images||[]){if(!/^assets\/journal\/[a-zA-Z0-9_-]+\.(jpe?g|png|webp|avif)$/.test(image.src)||!image.alt||!Number.isInteger(image.width)||!Number.isInteger(image.height)||image.width<1||image.height<1)throw Error('Invalid Journal image');await readFile(join(root,'public',image.src));}if(!p.title&&!p.images?.length)throw Error('Entry requires a title or photo');}
publicPosts.sort((a,b)=>b.date.localeCompare(a.date));
const image=(i,small=false)=>`<img src="${href(i.src)}" alt="${escape(i.alt)}" width="${i.width}" height="${i.height}" loading="lazy" decoding="async"${small?' class="journal-cover"':''}>`;
const label=p=>p.title||p.images[0].caption||`Photograph · ${p.date}`;
const routes=[{path:'journal/',title:'Journal · D-Bae',body:`<section class="journal-page"><p class="eyebrow">PERSONAL JOURNAL</p><h1>Outside the frame.</h1><p class="journal-deck">Photographs, everyday moments, and notes.</p>${publicPosts.length?`<label class="journal-search">Search journal<input type="search" id="journal-search" placeholder="Words, dates, or tags" aria-controls="journal-grid"></label><p id="journal-results" role="status" aria-live="polite"></p><div class="journal-grid" id="journal-grid">${publicPosts.map(p=>`<a class="journal-card" data-search="${escape([label(p),p.date,...(p.tags||[]),...(p.paragraphs||[])].join(' ').toLowerCase())}" href="${href('journal/'+p.slug+'/')}">${p.images?.length?image(p.images[0],true):'<div class="journal-text-cover" aria-hidden="true">Notes.</div>'}<time datetime="${p.date}">${p.date}</time><h2>${escape(label(p))}</h2>${(p.tags||[]).length?`<p class="journal-tags">${p.tags.map(escape).join(' · ')}</p>`:''}</a>`).join('')}</div>`:'<div class="journal-empty"><span aria-hidden="true">◌</span><p>A quiet space, for moments worth keeping.</p><small>No entries yet.</small></div>'}</section>`}];
for(const p of publicPosts){let paragraphs=p.paragraphs||[];if(p.bodyFile){if(!/^posts\/[a-z0-9-]+\.md$/.test(p.bodyFile))throw Error('Invalid Journal Markdown path');paragraphs=(await readFile(join(root,'journal',p.bodyFile),'utf8')).trim().split(/\n\s*\n/);}routes.push({path:'journal/'+p.slug+'/',title:label(p)+' · D-Bae',body:`<article class="journal-entry"><a class="journal-back" href="${href('journal/')}">← Journal</a><time datetime="${p.date}">${p.date}</time>${p.title?`<h1>${escape(p.title)}</h1>`:''}<div class="journal-prose">${paragraphs.map(t=>`<p>${escape(t).replaceAll('\n','<br>')}</p>`).join('')}</div>${(p.images||[]).map(i=>`<figure><a class="journal-photo" href="${href(i.src)}" aria-label="Expand photograph: ${escape(i.alt)}">${image(i)}</a>${i.caption?`<figcaption>${escape(i.caption)}</figcaption>`:''}</figure>`).join('')}</article>`});}
return routes;
}
